services:
  database:
    container_name: pern-store-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: pernstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [pernstore]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev        # <-- dùng file dev
    container_name: pern-store-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 10000
      DATABASE_URL: postgres://postgres:newpassword@database:5432/pernstore
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on: [database]
    ports:
      - "10000:10000"
    networks: [pernstore]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev        # <-- dùng file dev
    container_name: pern-store-client
    restart: unless-stopped
    environment:
      # để axios đọc được baseURL khi dev
      VITE_API_URL: http://localhost:10000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: [server]
    ports:
      - "5173:3000"
    networks: [pernstore]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pern-store-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "16543:80"
    depends_on: [database]
    networks: [pernstore]

networks:
  pernstore:
    driver: bridge

volumes:
  db:
    driver: local
