version: "3.8"

services:
  database:
    container_name: pern-store-db
    image: postgres:15
    restart: always
    env_file:
      - ./server/.env
    environment:
      POSTGRES_DB: pernstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pernstore

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pern-store-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      POSTGRES_HOST: database
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - database
    networks:
      - pernstore

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pern-store-client
    restart: unless-stopped
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - server
    networks:
      - pernstore

  pgadmin:
    image: dpage/pgadmin4
    container_name: pern-store-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - pernstore

networks:
  pernstore:
    driver: bridge

volumes:
  db:
    driver: local
